### ISSUE TITLE
Cannot find Docker image

### ISSUE THREAD

**Issue by Taeyoung96** [snt-arg/multi_s_graphs_docker#1]
@perezsaura-david  @miferco97  
Thanks for your great work!  

I'm trying to pull a docker image as it says in the readme, but I'm having the following problem.
```
Error response from daemon: pull access denied for sntarg/multi_s_graphs, 
repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```
When will docker images become public?

Thanks,

**Comment by hridaybavle** [comment]
@Taeyoung96 you will now be able to download the image.

**Comment by Taeyoung96** [comment]
@hridaybavle   
Thanks! The docker image is now available for download.
