### ISSUE TITLE
Docker image is not working

### ISSUE THREAD

**Issue by Taeyoung96** [snt-arg/multi_s_graphs_docker#2]
@miferco97 @hridaybavle  

I downloaded the image from [dockerhub](https://hub.docker.com/r/sntarg/multi_s_graphs) and tried to use it, but I encountered the following problem.  

```
docker: Error response from daemon: No command specified.
```

I had the same problem when I used the command `docker-compose up -d`  
and when I used the command `docker run -d --net host --name ms_graph sntarg/multi_s_graphs:latest`.  

Can I get a dockerfile or a description of how you created the docker image?  

Thanks,

**Comment by perezsaura-david** [comment]
Hello @Taeyoung96

Thank you for your feedback. We found an error uploading the docker image, so we uploaded it again. It should work properly now.

**Comment by Taeyoung96** [comment]
It works! Thanks for your reply. :smile:
